version: '2'
services:
  fcrepo:
    build: .
    image: moravianlibrary/fcrepo:3.8.1-akubra
    environment:
      - FEDORA_PASSWORD=fedoraAdmin
      - "FEDORA_DB_JDBC_URL=jdbc:postgresql://fedoraPostgres:5432/fedora3"
      - FEDORA_DB_USER=fedoraAdmin
      - FEDORA_DB_PASSWORD=fedoraAdmin
      - "RITRIPLES_DB_JDBC_URL=jdbc:postgresql://riTriplesPostgres:5432/riTriples"
      - RITRIPLES_DB_USER=fedoraAdmin
      - RITRIPLES_DB_PASSWORD=fedoraAdmin
    ports:
      - "8080:8080"
    links:
      - fedoraPostgres:fedoraPostgres
      - riTriplesPostgres:riTriplesPostgres
  fedoraPostgres:
    image: "postgres:9.3"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=fedora3
  riTriplesPostgres:
    image: "postgres:9.3"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=riTriples
