audioserver:
  image: nginx:latest
  volumes:
    - /data/audioserver:/data:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  environment:
    - "TZ=Europe/Prague"
  ports:
    - "80:80"
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always
