version: "2"
services:
  audioserver:
    image: nginx:latest
    volumes:
      - /mnt/audioserver:/data:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - "TZ=Europe/Prague"
      - VIRTUAL_HOST=audioserver.mzk.cz
      - LETSENCRYPT_HOST=audioserver.mzk.cz
      - LETSENCRYPT_EMAIL=daniel.secik@mzk.cz
      - HTTPS_METHOD=noredirect
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    restart:
      always

networks:
  default:
    external:
      name: ud_bridge
