nginx:
  build: ./openresty
  volumes:
    - /data/imageserver:/var/www/imageserver/data
  links:
    - imageserver:imageserver
  external_links:
    - "krameriusmzkcz_kramerius_1:kramerius.mzk.cz"
  environment:
    - "TZ=Europe/Prague"
    - VIRTUAL_HOST=imageserver.mzk.cz
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always

memcached:
  image: memcached:latest
  environment:
    - "TZ=Europe/Prague"
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always

imageserver:
  build: ./imageserver
  volumes:
    - /data/imageserver:/data
  environment:
    - "TZ=Europe/Prague"
  links:
    - memcached:memcached
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always
