version: "2"
services:
  nginx:
#    image: moravianlibrary/iipsrv-nginx:mzk
#    image: moravianlibrary/iipsrv-nginx:mzk-openresty
    build: ./openresty
    volumes:
      - /data/imageserver:/var/www/imageserver/data
#      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    environment:
      - "TZ=Europe/Prague"
      - VIRTUAL_HOST=imageserver.mzk.cz
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    restart:
      always

  memcached:
    image: memcached:latest
    command: memcached -m 512 -v
    environment:
      - "TZ=Europe/Prague"
    networks:
      default:
        aliases:
          - memcached.imageserver.mzk.cz
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    restart:
      always

  imageserver:
#    image: moravianlibrary/iipsrv-imageserver
    build: ./imageserver
    volumes:
      - /data/imageserver:/data
    networks:
      default:
        aliases:
          - iipimage.imageserver.mzk.cz
    environment:
      - "TZ=Europe/Prague"
      - "MEMCACHED_SERVERS=memcached.imageserver.mzk.cz"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    restart:
      always

networks:
  default:
    external:
      name: ud_bridge
